### ISSUE TITLE
部分数据问题

### ISSUE THREAD

**Issue by freeghter** [LittleYUYU/code_answer_inference#1]
作者你好，看了文章收获很多。其中关于训练数据data_partialcontext_shared_text_vocab_in_buckets.pickle中各个字段的格式不是很清楚。跟踪了一下data_utils.py中关于生成数据的部分。但是其中一些相关数据没有找到，例如代码中"%s_how_to_do_it_by_classifier_all_multiple_answer_codes_qid_partialtext_code_label_tuples.pickle"等数据数据，仓库中是否已经包含了这些数据呢？如果包含了是哪个文件，如果没有能不能提供一下。非常感谢！

**Comment by LittleYUYU** [comment]
@freeghter  你好， 感谢你对我们工作的兴趣！非常抱歉没有及时回复。

The training data you mentioned actually contains 4 lists, each for one bucket. The definition of the bucket size can be found in [run.py](https://github.com/LittleYUYU/StackOverflow-Question-Code-Dataset/blob/master/BiV_HNN/run.py#L114):
`# buckets: (text block number, word token number, query token number, code token number)
buckets_train = buckets_dev = buckets_test = [(2, 10, 22, 72), (2, 20, 34, 102), (2, 40, 34, 202), (2, 100, 34, 302)]`

The format of each example in a bucket contains 10 items:
`[example id, text blocks, the actual length of each text block, code blocks, the actual length of each code block, the query, the actual lengths of the query, code label (0/1), target code index, number of blocks]`.
1. `example id` should be a tuple of `(question post id, the index of the code snippet in the answer post)`.
2. Since one example has only two text blocks with one code block, the size of the `text blocks` and the `code blocks` are always 2 and 1, respectively. The `number of blocks` is within [1, 2, 3]. 
3. No need to use `target code index` (which is always 1).

The file "%s_how_to_do_it_by_classifier_all_multiple_answer_codes_qid_partialtext_code_label_tuples.pickle" contains the source data from the Stack Overflow dump (after tokenization). It should be with the same content but in a different format as the training data, so we do not provide it to confuse people.

However, please feel free to let me know if the above explanation about the training data format is unclear. Glad to say more!

**Comment by freeghter** [comment]
你好，通过你的回答加上对代码的阅读已经清楚了具体数据的格式。非常感谢。
________________________________
